### ISSUE TITLE
1. Create project

### ISSUE THREAD

**Issue by minhluu-pionero** [minhluu-pionero/admin-ec-app-vue3#1]
Use `bun` to create project vuejs with setup:
- typescript
- prettierrc
- eslin

**Comment by LongTran-Pionero** [comment]
em est 0.5h

**Comment by LongTran-Pionero** [comment]
em done ạ https://github.com/minhluu-pionero/admin-ec-app-vue3/pull/7

**Comment by minhluu-pionero** [comment]
Khi làm : chuyển trạng thái -> in progress
Làm xong: chuyển trạng thái -> testing
A sẽ check ở trạng thái testing để review
Trong pr thì link issue vào description
E làm theo luồng trên nhé, ko cần nhắn dong ở trong này nữa
