### ISSUE TITLE
2. Setup lib

### ISSUE THREAD

**Issue by minhluu-pionero** [minhluu-pionero/admin-ec-app-vue3#2]
- tailwindcss
- vuetify
- vue-router
- TanStack Query
- vee-validate

**Comment by LongTran-Pionero** [comment]
em est 0.5h ạ

**Comment by LongTran-Pionero** [comment]
https://github.com/minhluu-pionero/admin-ec-app-vue3/pull/8

**Comment by LongTran-Pionero** [comment]
em estimate lại tạo project và chỉnh sửa thư viện trong hôm nay ạ

**Comment by minhluu-pionero** [comment]
Ghi ngày vào e
