### ISSUE TITLE
3. Create auth layout

### ISSUE THREAD

**Issue by minhluu-pionero** [minhluu-pionero/admin-ec-app-vue3#3]
## Task Content
Create auth layout with 

- [x] login page
- [x] forgot password
## Estimate
2h

**Comment by minhluu-pionero** [comment]
@LongTran-Pionero thêm deadline date vào đi e

**Comment by LongTran-Pionero** [comment]
vâng ạ em đưa task này sang test rồi ạ

**Comment by minhluu-pionero** [comment]
Khi nào merge mới là done nhé

**Comment by LongTran-Pionero** [comment]
vâng ạ
